# Inspired by:
# https://github.com/zopefoundation/meta/tree/master/config/pure-python
name: tests

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: "6 14 * * 3"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7,3.6,3.7,3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.*', '*.cfg') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run buildout
        run: buildout
      - name: Run code analysis
        run: ./bin/code-analysis
      - name: Run tests
        run: ./bin/test
